CREATE TABLE address (
    id VARCHAR(36) UNIQUE PRIMARY KEY NOT NULL,
    status bit NOT NULL,
    oprettet timestamp NOT NULL,
    aendret timestamp NOT NULL,
    vejkode INT UNSIGNED NOT NULL ,
    vejnavn text NOT NULL,
    addresseringsvejnavn text NOT NULL,
    husnr text NOT NULL,
    etage text,
    doer text,
    supplerendebynavn text,
    postnr INT UNSIGNED NOT NULL,
    postnrnavn text NOT NULL,
    stormodtagerpostnr INT UNSIGNED,
    stormodtagerpostnrnavn text,
    kommunekode INT UNSIGNED NOT NULL,
    kommunenavn text NOT NULL,
    ejerlavkode INT UNSIGNED NOT NULL,
    ejerlavnavn text NOT NULL,
    matrikelnr TEXT NOT NULL,
    esrejendomsnr INT UNSIGNED NOT NULL,
    etrs89koordinat_oest double NOT NULL,
    etrs89koordinat_nord double NOT NULL,
    wgs84koordinat_bredde double NOT NULL,
    wgs84koordinat_laengde double NOT NULL,
    noejagtighed VARCHAR(1) NOT NULL,
    kilde INT UNSIGNED NOT NULL,
    tekniskstandard VARCHAR(2) NOT NULL,
    tekstretning double NOT NULL,
    ddkn_m100 text NOT NULL,
    ddkn_km1 text NOT NULL,
    10km_624_54 text NOT NULL,
    adressepunktaendringsdato timestamp NOT NULL,
    adgangsadresseid VARCHAR(36) NOT NULL,
    adgangsadresse_status bit NOT NULL,
    adgangsadresse_oprettet timestamp NOT NULL,
    adgangsadresse_aendret timestamp NOT NULL,
    regionskode INT UNSIGNED NOT NULL,
    regionsnavn text NOT NULL,
    jordstykke_ejerlavnavn text NOT NULL,
    kvhx text NOT NULL,
    sognekode INT UNSIGNED NOT NULL,
    sognenavn text NOT NULL,
    politikredskode INT UNSIGNED NOT NULL,
    politikredsnavn text NOT NULL,
    retskredskode INT UNSIGNED NOT NULL,
    retskredsnavn text NOT NULL,
    opstillingskredskode INT UNSIGNED NOT NULL,
    opstillingskredsnavn text NOT NULL,
    zone text NOT NULL,
    jordstykke_ejerlavkode INT UNSIGNED NOT NULL,
    jordstykke_matrikelnr text NOT NULL,
    jordstykke_esrejendomsnr INT UNSIGNED NOT NULL,
    kvh text NOT NULL,
    hoejde double NOT NULL,
    adgangspunktid VARCHAR(36) NOT NULL,
    vejpunkt_id VARCHAR(36) NOT NULL,
    vejpunkt_kilde text NOT NULL,
    vejpunkt_noejagtighed VARCHAR(1) NOT NULL,
    vejpunkt_tekniskstandard VARCHAR(2) NOT NULL,
    vejpunkt_x double NOT NULL,
    vejpunkt_y double NOT NULL,
    afstemningsomraadenummer INT UNSIGNED NOT NULL,
    afstemningsomraadenavn text NOT NULL,
    brofast bit NOT NULL,
    supplerendebynavn_dagi_id INT UNSIGNED,
    navngivenvej_id VARCHAR(36) NOT NULL,
    menighedsraadsafstemningsomraadenummer INT UNSIGNED NOT NULL,
    menighedsraadsafstemningsomraadenavn text NOT NULL,
    vejpunkt_aendret timestamp NOT NULL,
    ikrafttraedelse timestamp NOT NULL,
    nedlagt bit,
    adgangsadresse_ikrafttraedelse timestamp NOT NULL,
    adgangsadresse_nedlagt timestamp,
    adgangsadresse_darstatus INT UNSIGNED NOT NULL,
    darstatus INT UNSIGNED NOT NULL,
    storkredsnummer INT UNSIGNED NOT NULL,
    storkredsnavn text NOT NULL,
    valglandsdelsbogstav VARCHAR(1) NOT NULL,
    valglandsdelsnavn text NOT NULL,
    landsdelsnuts3 text NOT NULL,
    landsdelsnavn text NOT NULL,
    betegnelse text NOT NULL
);
